Switched to Activity Result API
vksdk/vk-sdk-android pull request #5
Opened 2022-12-18 21:31 UTC by DrRey

2022-12-23 16:24 UTC, petersamokhin requested changes

2022-12-23 16:24 UTC, petersamokhin commented on auth/src/main/kotlin/com/petersamokhin/vksdk/android/auth/VkAuth.kt
> +    private val resultLaunchers = mutableMapOf<ComponentActivity, ActivityResultLauncher<Intent>>()
let's use weak references instead

2022-12-23 16:24 UTC, petersamokhin commented on auth/src/main/kotlin/com/petersamokhin/vksdk/android/auth/VkAuth.kt
> +            activity,
let's pls refactor it to use the named parameter names everywhere like here

2022-12-24 20:12 UTC, DrRey commented on auth/src/main/kotlin/com/petersamokhin/vksdk/android/auth/VkAuth.kt
> +    private val resultLaunchers = mutableMapOf<ComponentActivity, ActivityResultLauncher<Intent>>()
changed to WeakHashMap

2022-12-28 21:59 UTC, closed without merging